apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: first-vol
  volumes:
  - name: first-vol
    persistentVolumeClaim:
      claimName: first-persistentvolumeclaim
