apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-persistentvolumeclaim
spec:
  storageClassName: manual      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
