apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-persistentvolume
spec:
  storageClassName: manual
  capacity:
    storage: "3Gi"
  accessModes:
  - ReadWriteOnce    
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: vol-0f84612c4149487de
  
