apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  volumes:
  - name : first-vol
    secret:
      secretName: first-secret    

  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: first-vol
      mountPath: /app 
