apiVersion: v1
kind: Pod
metadata: 
  name: cm-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: first-volume
        mountPath: /app        
  volumes:
  - name: first-volume
    configMap:
      name: first-cm
