apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-rs
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      env: dev      
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:       
        env: dev  
    spec:
      containers:    
      - name: nginx
        image: tomcat:9
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - blue
